### ISSUE TITLE
#show: letter.with(header: []) question

### ISSUE THREAD

**Issue by ondohotola** [ludwig-austermann/typst-din-5008-letter#2]
Looks nice.

How do I get something like

```
Dr Eberhard W Lisse
    Frauenarzt
```
centered into the middle of the page?

Currently playing with the the `nice_defaults.typ` example

```typc
header: [#align(center)[Dr Eberhard W Lisse\ Frauenarzt]\ #line(width: 100%)],
```

shows it centered from the beginning of the text area to where 'sender.address` starts and not on the whole width of the text area.

**Comment by ludwig-austermann** [comment]
I think in the DIN standard, a width of max. 75mm is required. That's why your content would be centered, but inside a block of width 75mm.

Take a look at the `infoheader` function, to customize it to your liking, but I think this template should still follow the DIN specs. However, maybe another option should be added later.
